version: "3"

services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=R00Tpostgres
      - POSTGRES_DB=poc-transaction
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: